language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - sudo apt install -y postgresql-server-dev-9.6
  # install deps
  # temp fix for https://github.com/pypa/setuptools/issues/3293
  - pip install --upgrade importlib-metadata>=0.21
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install fastcluster
  - pip list

script:
  - py.test --cov-report term-missing --cov-config .coveragerc --cov=blitzortung
  - py.test -v --cov blitzortung --cov-report term-missing

after_success:
  - coveralls
