language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - sudo apt install -y postgresql-server-dev-9.6
  # install deps
  # temp fix for https://github.com/pypa/setuptools/issues/3293
  - pip install --upgrade importlib-metadata>=0.21
  - pip install -r requirements.txt
  - pip install fastcluster
  - pip list

script:
  - pytest --cov-report xml:coverage.xml --cov-report term --cov=blitzortung tests

after_success:
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
