[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
disallow_incomplete_defs = False
check_untyped_defs = True
ignore_missing_imports = True

[mypy-tests.*]
ignore_errors = True

[mypy-pyproj.*]
ignore_missing_imports = True

[mypy-shapely.*]
ignore_missing_imports = True

[mypy-psycopg2.*]
ignore_missing_imports = True

[mypy-psycopg2cffi.*]
ignore_missing_imports = True

[mypy-fasteners.*]
ignore_missing_imports = True

[mypy-txpostgres.*]
ignore_missing_imports = True

[mypy-injector.*]
ignore_missing_imports = True

[mypy-websocket_client.*]
ignore_missing_imports = True

[mypy-stopit.*]
ignore_missing_imports = True

[mypy-statsd.*]
ignore_missing_imports = True

[mypy-geoip2.*]
ignore_missing_imports = True

[mypy-incremental.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True
